name: CI
on:
  push:
    branches:
      - develop

jobs:
  build:
    if: github.repository == 'a928230991/reference'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install
      - run: npm run build

      - name: Generate Contributors Images
        uses: a928230991/github-action-contributors@develop
        id: contributors
        with:
          filter-author: (renovate\[bot\]|renovate-bot|dependabot\[bot\])
          output: dist/CONTRIBUTORS.svg
          avatarSize: 42

      - name: Modify CONTRIBUTING.md
        uses: a928230991/github-action-modify-file-content@develop
        with:
          path: CONTRIBUTING.md
          body: |
            ${{steps.contributors.outputs.htmlList}}

      - name: Modify README.md
        uses: a928230991/github-action-modify-file-content@develop
        with:
          path: README.md
          body: |
            ${{steps.contributors.outputs.htmlList}}

      - name: Create Tag
        id: create_tag
        uses: a928230991/create-tag-action@develop
        with:
          package-path: ./package.json

      - name: gh-pages README.md
        working-directory: dist
        run: |
          cat << "EOF" > README.md
          Website: https://a928230991.github.io/reference
          ## Docker

          [![Buy me a coffee](https://img.shields.io/badge/Buy%20me%20a%20coffee-048754?logo=buymeacoffee)](https://a928230991.github.io/#/sponsor) [![Docker Image Version (latest by date)](https://img.shields.io/docker/v/a928230991/reference)](https://hub.docker.com/r/a928230991/reference) [![Docker Image Size (latest by date)](https://img.shields.io/docker/image-size/a928230991/reference)](https://hub.docker.com/r/a928230991/reference) [![Docker Pulls](https://img.shields.io/docker/pulls/a928230991/reference)](https://hub.docker.com/r/a928230991/reference)

          轻松通过 `docker` 部署 `Quick Reference` 网站。

          ```bash
          docker pull a928230991/reference
          ```

          ```bash
          docker run --name reference --rm -d -p 9667:3000 a928230991/reference:latest
          # Or
          docker run --name reference -itd -p 9667:3000 a928230991/reference:latest
          ```

          在浏览器中访问以下 URL

          ```bash
          http://localhost:9667/
          ```
          EOF

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          commit_message: ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Generate Changelog
        id: changelog
        uses: a928230991/changelog-generator@develop
        with:
          filter-author: (小弟调调™|github-actions-bot|\@github\-actions\-bot|dependabot|renovate\\[bot\\]|dependabot\\[bot\\]|Renovate Bot)
          filter: (^[\s]+?[R|r]elease)|(^[R|r]elease)

      - name: Create Release
        uses: ncipollo/release-action@v1
        if: steps.create_tag.outputs.successful
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.create_tag.outputs.version }}
          tag: ${{ steps.create_tag.outputs.version }}
          body: |
            [![Buy me a coffee](https://img.shields.io/badge/Buy%20me%20a%20coffee-048754?logo=buymeacoffee)](https://a928230991.github.io/#/sponsor) 
            
            Documentation ${{ steps.changelog.outputs.tag }}: https://raw.githack.com/a928230991/reference/${{ steps.changelog.outputs.gh-pages-short-hash }}/index.html  
            Comparing Changes: ${{ steps.changelog.outputs.compareurl }}  

            ${{ steps.changelog.outputs.changelog }}

            ## Docker
            [![Docker Image Version (latest by date)](https://img.shields.io/docker/v/a928230991/reference)](https://hub.docker.com/r/a928230991/reference) [![Docker Image Size (latest by date)](https://img.shields.io/docker/image-size/a928230991/reference)](https://hub.docker.com/r/a928230991/reference) [![Docker Pulls](https://img.shields.io/docker/pulls/a928230991/reference)](https://hub.docker.com/r/a928230991/reference)

            轻松通过 `docker` 部署 `Quick Reference` 网站。

            ```bash
            docker pull a928230991/reference
            ```

            ```bash
            docker run --name reference --rm -d -p 9667:3000 a928230991/reference:latest
            # Or
            docker run --name reference -itd -p 9667:3000 a928230991/reference:latest
            ```

            在浏览器中访问以下 URL

            ```bash
            http://localhost:9667/
            ```

      # Create Docker Image
      - uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image:latest
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          tags: a928230991/reference:latest

      - name: Build and push image:tags
        uses: docker/build-push-action@v3
        if: steps.create_tag.outputs.successful
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          tags: a928230991/reference:${{steps.changelog.outputs.version}}

      # # Create Docker Image in Github
      # - name: Login to the GitHub Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build and push image:latest
      #   uses: docker/build-push-action@v3
      #   with:
      #     push: true
      #     context: .
      #     platforms: linux/amd64,linux/arm64
      #     tags: ghcr.io/a928230991/reference:latest

      # - name: Build and push image:tags
      #   uses: docker/build-push-action@v3
      #   if: steps.create_tag.outputs.successful
      #   with:
      #     push: true
      #     context: .
      #     platforms: linux/amd64,linux/arm64
      #     tags: ghcr.io/a928230991/reference:${{steps.changelog.outputs.version}}

      # # Create Docker Image in Github
      # - name: Login to GitHub registry
      #   run: echo ${{ github.token }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # - name: Build docker image
      #   run: docker build -t ghcr.io/a928230991/reference:latest .

      # - name: Publish to GitHub registry
      #   run: docker push ghcr.io/a928230991/reference:latest

      # - name: Tag docker image (beta) and publish to GitHub registry
      #   if: steps.create_tag.outputs.successful
      #   run: |
      #     echo "version: v${{ steps.changelog.outputs.version }}"
      #     docker tag ghcr.io/a928230991/reference:latest ghcr.io/a928230991/reference:${{steps.changelog.outputs.version}}
      #     docker push ghcr.io/a928230991/reference:${{steps.changelog.outputs.version}}

      # # Create Docker Image
      # - name: Docker login
      #   run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build reference image
      #   run: docker image build -t reference .

      # - name: Tags & Push image(latest)
      #   run: |
      #     echo "DOCKER_USER: ${{ secrets.DOCKER_USER }}"
      #     docker tag reference ${{ secrets.DOCKER_USER }}/reference:latest
      #     docker push ${{ secrets.DOCKER_USER }}/reference:latest

      # - name: Tags & Push image
      #   if: steps.create_tag.outputs.successful
      #   run: |
      #     echo "outputs.tag - ${{ steps.changelog.outputs.version }}"
      #     docker tag reference ${{ secrets.DOCKER_USER }}/reference:${{steps.changelog.outputs.version}}
      #     docker push ${{ secrets.DOCKER_USER }}/reference:${{steps.changelog.outputs.version}}
